name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install npm dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: "dist/"
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
